### ISSUE TITLE
Useless Package? 

### ISSUE THREAD

**Issue by yesIamFaded** [junedomingo/react-native-rename#75] opened 2019-04-30 07:05 UTC
This package doenst seem to be maintained well. 

1. After running the package there are still hundrets of files that have the old name of your app.

2. It deletes your MainActivity.java and your MainApplication.java files which destroys your whole app. 

Does anyone have a good resonable solution on how to rename your app ( for android ) without destroying your whole project and making it harder then it should be?

**Comment by ajcrites** [comment] 2019-06-24 16:25
Seems to be a duplicate of #72, but if you have a more specific issue (or issues) please reopen with reproduction steps. You can open multiple issues for separate concerns.

**Closed by ajcrites** 2019-06-24 16:25 UTC
