### ISSUE TITLE
Some files are being deleted

### ISSUE THREAD

**Issue by brunolemos** [junedomingo/react-native-rename#47] opened 2018-03-08 05:24 UTC
- org
  - brunolemos
    - app
      - modules [DELETED]
        - MyCustomModule [DELETED]
          - CustomModule.java [DELETED]
          - CustomPackage.java [DELETED]
      - MainActivity.java (package name renamed correctly)
      - MainApplication.java (package name renamed correctly)

macOS
Latest version of everything

**Comment by pesarkhobeee** [comment] 2018-03-14 06:50
I have same problem too! you can see that in my screenshot
![screenshot from 2018-03-14 07-39-16](https://user-images.githubusercontent.com/147461/37387363-5d02f6be-275c-11e8-85dc-52b47e3e4dd3.png)

**Comment by mouthzipper** [comment] 2018-04-09 15:11
I have same problem.

**Comment by ajcrites** [comment] 2018-11-01 13:13
Duplicate of #55

**Comment by adam-buckley** [comment] 2018-11-12 01:45
Still having this issue as of v2.3.2. **Note this happens regardless of whether a new bundle identifier is specified or if the bundle identifier is different to the original**

I.e. both commands remove the files:
```sh
// Original app name was "SkeletonReactNativeApp", bundle was "com.skeletonreactnativeapp"
react-native-rename "CmsSkeletonApp"
react-native-rename "CmsSkeletonApp" -b com.twopisoftware.cmsskeletonapp
```

Custom Android classes ("AppKiller" in git diff screenshot) are being deleted, not sure why _anything_ should be destroyed by running the react-native-rename command. In theory I can just discard the changes in git that remove the files, but I would also have to manually rename the package in those files.

OS: Ubuntu 18.10
npm -v: 5.8.0

![screenshot](https://user-images.githubusercontent.com/1585392/48321650-e3137500-e677-11e8-8099-b60f2eb64795.png)

**Comment by ajcrites** [comment] 2018-11-12 01:48
@adam-buckley the fix for this is in 2.4. Can you install the @next tag and check that?

**Comment by ajcrites** [comment] 2018-11-13 19:00
Reopening since this is still an issue with unspecified files.

**Comment by ajcrites** [comment] 2018-11-13 19:47
This should now be fixed in 2.4.0-rc3

**Closed by ajcrites** 2018-11-13 19:47 UTC

**Comment by adam-buckley** [comment] 2018-11-13 22:19
I have 50% good news, it works now when not specifying the bundle identifier. But when giving the bundle identifier the rename now removes all Java files.

**Comment by adam-buckley** [comment] 2018-11-14 03:41
Ah I worked it out, my previous testing ended up creating a bunch of blank folders (since I was resetting the failed rename attempts in git, folders aren't cleaned up), and I think my bundle identifier conflicted with one of these empty folders, once I removed them everything worked fine.

**Comment by GiannKarlo** [comment] 2021-02-04 12:53
This is still an issue in 2.7 version.
