### ISSUE TITLE
Removes java files under old package name

### ISSUE THREAD

**Issue by cihadturhan** [junedomingo/react-native-rename#40] opened 2017-12-22 15:05 UTC
I have a RN projects created with create-rn-app package but modified. 
I ran your tool and realized it removes the files under
`/android/app/src/java/old/package/name/MainActivity.java`
`/android/app/src/java/old/package/name/MainApplication.java`

and creates a folder
`/android/app/src/java/new/package/name/`

I'm on windows, node 8.3, npm 5.3.0
Let me know if I can provide further details.

**Comment by jjzazuet** [comment] 2018-01-29 03:44
@cihadturhan I believe this an expected side effect, since java source files must belong to the new package name. Hence probably not an issue (perhaps `react-native link` may suffer because of this, but I still need to try it out). Cheers!

**Comment by dreindoRT** [comment] 2018-03-14 07:33
Me too, after rename MainApplication.java and MainActivity.java are removed...

**Comment by SirPhemmiey** [comment] 2018-06-14 18:29
Any fix for this?

**Comment by ajcrites** [comment] 2018-11-01 13:18
Duplicate of #55

**Closed by ajcrites** 2018-11-01 13:18 UTC
