### ISSUE TITLE
Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by barjas** [junedomingo/react-native-rename#60] opened 2018-10-24 11:06 UTC
im getting this with react native 0.56

```
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to lookup in current state: Shutting Down
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ReactNativeKit.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```
any idea?

**Comment by ajcrites** [comment] 2018-11-01 12:22
Duplicate of #25

**Closed by ajcrites** 2018-11-01 12:22 UTC
