### ISSUE TITLE
RN 57 fresh install force close 

### ISSUE THREAD

**Issue by ajiehatajie** [junedomingo/react-native-rename#58] opened 2018-09-21 06:43 UTC
i install rn 57 and then change the package -b
and apps cannot open

**Comment by vikaskbh** [comment] 2018-10-03 17:57
I am also using RN 0.57. Looks like it deleted MainActivity.java that's why its crashing. i had full backup. so didn't hurt much.

**Comment by ajcrites** [comment] 2018-11-01 13:03
Duplicate of #55

**Closed by ajcrites** 2018-11-01 13:03 UTC
