### ISSUE TITLE
why ios path is error

### ISSUE THREAD

**Issue by iosLongFeng** [junedomingo/react-native-rename#64] opened 2018-11-14 10:27 UTC
12345:zhaoxin longfeng$ react-native-rename "zhaoxin2"
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin1
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin1-tvOS
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin1-tvOSTests
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin1.xcodeproj
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin2.xcodeproj/xcshareddata/xcschemes/zhaoxin1-tvOS.xcscheme
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin2.xcodeproj/xcshareddata/xcschemes/zhaoxin1.xcscheme
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin1Tests
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin2Tests/zhaoxin1Tests.m
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin1.xcworkspace
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/longfeng/Desktop/renameTest/zhaoxin/ios/zhaoxin2/zhaoxin1.entitlements
Ignore above error if this file doesn't exist
/android/app/src/main/res/values/strings.xml MODIFIED
/index.js MODIFIED
/package.json MODIFIED
/app.json MODIFIED
/android/settings.gradle MODIFIED
/ios/Podfile MODIFIED
/app.json MODIFIED
/android/app/BUCK MODIFIED
/android/app/src/main/java/com/zhaoxin2/MainActivity.java MODIFIED
/android/app/src/main/java/com/zhaoxin2/MainApplication.java MODIFIED
/android/app/src/main/java/com/zhaoxin2/MainActivity.java MODIFIED
/android/app/build.gradle MODIFIED
/android/app/src/main/java/com/zhaoxin2/MainApplication.java MODIFIED
/android/app/src/main/AndroidManifest.xml MODIFIED
Done removing previous bundle directory.
Done removing builds.
APP SUCCESSFULLY RENAMED TO "zhaoxin2"! 🎉 🎉 🎉
Podfile has been modified, please run "pod install" inside ios directory.
Please make sure to run "watchman watch-del-all" and "npm start --reset-cache" before running the app.

**Comment by MehranAbghari** [comment] 2018-11-14 12:08
Duplicate. #43 
I have the same issue.

**Comment by ajcrites** [comment] 2018-11-20 22:54
Closing as it is a duplicate. I'd appreciate if someone could take a look since I haven't been able to reproduce this myself yet.

**Closed by ajcrites** 2018-11-20 22:54 UTC
