### ISSUE TITLE
Custom Bundle Identifier delete main java files

### ISSUE THREAD

**Issue by vuphuctho** [junedomingo/react-native-rename#54] opened 2018-05-23 12:39 UTC
**Version used:**
```
    "react": "16.0.0",
    "react-native": "0.51.0"
    "react-native-version": "2.2.2",
```

**What happened:**
- In folder `android/app/src/main/java/my/custom/bundleIdentifier` there were 2 files `MainActivity.java` and `MainApplication.java`
- Run `react-native-version newName -b my.custom.bundleIdentifier`

**Observation:**
After react-native-rename finished, the two above file are deleted. So when I create an apk from the app and install to device, app always crashes when I try to open. No error message, no bug report (I use Bugsnag to track bugs and crash exceptions)

**Comment by baselbj** [comment] 2018-05-24 23:56
same issue

**Comment by SirPhemmiey** [comment] 2018-06-14 18:31
This is a real bug....There's no fix until now

**Comment by geminiyellow** [comment] 2018-08-21 03:50
yes, same error.

**Comment by vgb0332** [comment] 2018-09-27 09:51
it just two files. just copy the older ones and paste with the newer package name corrected on both file. Easy and works fine.

**Comment by ajcrites** [comment] 2018-11-01 12:55
Duplicate of #55

**Closed by ajcrites** 2018-11-01 12:55 UTC
