### ISSUE TITLE
(node:847) Warning: Accessing non-existent property + Please try a different name.

### ISSUE THREAD

**Issue by jacow** [junedomingo/react-native-rename#108] opened 2020-09-21 00:42 UTC
(node:847) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:847) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:847) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
Please try a different name.

**Comment by kalyanijamunkar10** [comment] 2020-09-24 12:36
@jacow any luck on this.

**Comment by ebeliejinfren** [comment] 2020-10-10 23:28
same problem

**Comment by cyb3rsalih** [comment] 2020-10-14 10:58
Is there any update? Can't find any alternative for this tool

**Comment by Yrsafam** [comment] 2020-10-23 08:31
I had an assumption that this was caused by the node js version, but switching to version `10.22.3` the problem remained.

```
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '/Users/user/Documents/project/projectName/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by vomchik** [comment] 2020-10-23 19:12
Should be fixed in the new release `2.5.0`

**Comment by Yrsafam** [comment] 2020-10-24 07:32
Unfortunately, this fix did not help in my situation. Guys who have encountered the same problem, please share the results.

**Comment by vomchik** [comment] 2020-10-27 12:38
@Yrsafam  you describe how you run the library? Also share your env info, NodeJS version, OS, etc.

**Comment by Yrsafam** [comment] 2020-11-04 02:59
@vomchik 
usage: followed the library documentation
NodeJS(use NVM):
14.13.1
10.22.1
"react-native": "0.62.2"
"react-native-rename": "2.5.0"
OS: Windows 10 version 20H2

**Comment by vomchik** [comment] 2020-11-06 12:51
@Yrsafam thanks. looks like it related to os version. will try to figure out...

**Comment by dekameron22** [comment] 2020-11-20 10:43
is there any update?
experiencing same issue.

**Comment by jamesjara** [comment] 2021-04-07 03:30
had the same issue.
its happeing when having expo as env.

add this
 node_modules/react-native-rename/lib/index.js:98:42

```
-  var currentAppName = appConfig.name;
+  appConfig = appConfig.expo;
+  var currentAppName = appConfig.name;
```

**Comment by junedomingo** [comment] 2022-12-26 09:24
Closing, check v3 now.

**Closed by junedomingo** 2022-12-26 09:24 UTC
Labels: bug

**Comment by iampato** [comment] 2023-02-08 12:37
Using node 19.3.X same issue

**Comment by junedomingo** [comment] 2023-02-08 12:38
@iampato What version react-native-rename are you one?

**Comment by junedomingo** [comment] 2023-02-08 12:48
@iampato try the latest version v3.2.12
